"""add post favorite and share

Revision ID: de8a0eb1fda1
Revises: 4d2c1a9b8e7f
Create Date: 2026-04-08 13:38:31.153122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de8a0eb1fda1'
down_revision: Union[str, None] = '4d2c1a9b8e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_post_favorites_user_post')
    )
    op.create_index('ix_post_favorites_post_created_at', 'post_favorites', ['post_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_post_favorites_post_id'), 'post_favorites', ['post_id'], unique=False)
    op.create_index('ix_post_favorites_user_created_at', 'post_favorites', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_post_favorites_user_id'), 'post_favorites', ['user_id'], unique=False)
    op.add_column('posts', sa.Column('favorite_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('posts', sa.Column('share_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'share_count')
    op.drop_column('posts', 'favorite_count')
    op.drop_index(op.f('ix_post_favorites_user_id'), table_name='post_favorites')
    op.drop_index('ix_post_favorites_user_created_at', table_name='post_favorites')
    op.drop_index(op.f('ix_post_favorites_post_id'), table_name='post_favorites')
    op.drop_index('ix_post_favorites_post_created_at', table_name='post_favorites')
    op.drop_table('post_favorites')
    # ### end Alembic commands ###
